### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/smext-NetInfoManager#1]
Hi! I got this error when trying to compile (couldn't figure this out by myself)
/sm/extensions/smext-NetInfoManager-main/extension.cpp:59:14: error: expected initializer before 'OnFrameDataUpdated'
 void __cdecl OnFrameDataUpdated()
              ^
![image](https://user-images.githubusercontent.com/4301144/144727946-690c29bf-54df-43a1-8bf9-28dedefbda63.png)

**Comment by yourmnbbn** [comment]
Hey, on gcc, attributes like naked and calling conventions are only supported on limited architectures like ARM, etc. So the implementation cannot be compiled on gcc. You should use clang to compile this.

**Comment by toorisrael** [comment]
Thank you, that worked!
