### ISSUE TITLE
Build failed: netinfomgr.ext.2.csgo/extension.o

### ISSUE THREAD

**Issue by edgar009955** [yourmnbbn/smext-NetInfoManager#2]
ambuild/extension.cpp:59:14: error: expected initial                               izer before ‘OnFrameDataUpdated’
   59 | void __cdecl OnFrameDataUpdated()
      |              ^~~~~~~~~~~~~~~~~~
ambuild/extension.cpp:82:11: error: expected constru                               ctor, destructor, or type conversion before ‘(’ token
   82 | __declspec(naked) void HostRunFrameHookHandler()
      |           ^
ambuild/extension.cpp: In member function ‘virtual b                               ool NetInfoMgr::SDK_OnLoad(char*, size_t, bool)’:
ambuild/extension.cpp:134:102: error: ‘HostRunFrameH                               ookHandler’ was not declared in this scope
  134 |     g_HostRunFrameHook = new subhook::Hook((void*)((uintptr_t)g_pHostRun                               Frame + HOOK_OFFSET), (void*)HostRunFrameHookHandler);

**Comment by yourmnbbn** [comment]
Just like #1, you should use clang to compile this extension.
