### ISSUE TITLE
gamedata update

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/smext-NetInfoManager#4]
Hi! Since last CSGO update gamedata is broken. Could you please update?

**Comment by stefanx111** [comment]
+1

**Comment by yourmnbbn** [comment]
Hello, It's currently working in progress. Last update breaks the original implementation so it would take a little more time than just update the gamedata.

**Comment by yourmnbbn** [comment]
Latest commits has refactored the implementation and updated the signatures and offsets. And all been tested. Release has been updated.
